const words = [
  {
    id: "el_animal",
    text: "animal",
    phonetic: "/ˈænɪml/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "n.",
    meaning: "动物",
    example: "The panda is my favorite animal.",
    collocation: "wild animal",
    note: "小学常见名词，注意复数 animals。"
  },
  {
    id: "el_weather",
    text: "weather",
    phonetic: "/ˈweðə(r)/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "n.",
    meaning: "天气",
    example: "The weather is sunny today.",
    collocation: "good weather",
    note: "不可数名词，不说 a weather。"
  },
  {
    id: "el_library",
    text: "library",
    phonetic: "/ˈlaɪbrəri/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "n.",
    meaning: "图书馆",
    example: "I read books in the library.",
    collocation: "school library",
    note: "注意拼写，不要漏掉 r。"
  },
  {
    id: "el_important",
    text: "important",
    phonetic: "/ɪmˈpɔːtnt/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "adj.",
    meaning: "重要的",
    example: "English is an important subject.",
    collocation: "be important to",
    note: "常用于表达某事很重要。"
  },
  {
    id: "el_because",
    text: "because",
    phonetic: "/bɪˈkɒz/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "conj.",
    meaning: "因为",
    example: "I like English because it is useful.",
    collocation: "because of",
    note: "because 后接句子，because of 后接名词。"
  },
  {
    id: "el_careful",
    text: "careful",
    phonetic: "/ˈkeəfl/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "adj.",
    meaning: "仔细的；小心的",
    example: "Be careful when you cross the road.",
    collocation: "be careful with",
    note: "常用于提醒注意安全或细节。"
  },
  {
    id: "el_finish",
    text: "finish",
    phonetic: "/ˈfɪnɪʃ/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "v.",
    meaning: "完成；结束",
    example: "I finish my homework before dinner.",
    collocation: "finish doing sth.",
    note: "finish 后面接动词 ing 形式。"
  },
  {
    id: "el_healthy",
    text: "healthy",
    phonetic: "/ˈhelθi/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "adj.",
    meaning: "健康的",
    example: "Fruit and vegetables are healthy food.",
    collocation: "keep healthy",
    note: "注意 healthy 是形容词，health 是名词。"
  },
  {
    id: "el_question",
    text: "question",
    phonetic: "/ˈkwestʃən/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "n.",
    meaning: "问题",
    example: "Can I ask you a question?",
    collocation: "answer a question",
    note: "常和 ask、answer 搭配。"
  },
  {
    id: "el_together",
    text: "together",
    phonetic: "/təˈɡeðə(r)/",
    level: "elementary",
    book: "小学基础",
    partOfSpeech: "adv.",
    meaning: "一起",
    example: "We study together after school.",
    collocation: "work together",
    note: "表示共同做某事。"
  },
  {
    id: "hs_approach",
    text: "approach",
    phonetic: "/əˈprəʊtʃ/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "方法；接近；处理",
    example: "We need a new approach to solving this problem.",
    collocation: "an approach to doing sth.",
    note: "阅读中常考“方法、途径”，不只是“接近”。"
  },
  {
    id: "hs_concern",
    text: "concern",
    phonetic: "/kənˈsɜːn/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "担心；涉及；关心",
    example: "The report concerns the safety of students.",
    collocation: "be concerned about",
    note: "既可表示“担忧”，也可表示“涉及”。"
  },
  {
    id: "hs_available",
    text: "available",
    phonetic: "/əˈveɪləbl/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "adj.",
    meaning: "可获得的；有空的",
    example: "Tickets are available online.",
    collocation: "be available to sb.",
    note: "常用于资源、时间、服务是否可用。"
  },
  {
    id: "hs_account",
    text: "account",
    phonetic: "/əˈkaʊnt/",
    level: "high_school",
    book: "熟词生义",
    partOfSpeech: "n./v.",
    meaning: "账户；描述；解释；占比",
    example: "Students account for 60 percent of the visitors.",
    collocation: "account for",
    note: "account for 常考“解释”或“占……比例”。"
  },
  {
    id: "hs_analyze",
    text: "analyze",
    phonetic: "/ˈænəlaɪz/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "v.",
    meaning: "分析",
    example: "We need to analyze the reasons for the change.",
    collocation: "analyze a problem",
    note: "阅读和写作中常用于分析原因、数据和问题。"
  },
  {
    id: "hs_benefit",
    text: "benefit",
    phonetic: "/ˈbenɪfɪt/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "好处；使受益",
    example: "Reading benefits students in many ways.",
    collocation: "benefit from",
    note: "benefit from 表示“从……中受益”。"
  },
  {
    id: "hs_challenge",
    text: "challenge",
    phonetic: "/ˈtʃælɪndʒ/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "挑战；质疑",
    example: "The new task is a real challenge for us.",
    collocation: "face a challenge",
    note: "既可作名词，也可作动词。"
  },
  {
    id: "hs_evidence",
    text: "evidence",
    phonetic: "/ˈevɪdəns/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n.",
    meaning: "证据",
    example: "There is clear evidence that exercise improves sleep.",
    collocation: "clear evidence",
    note: "通常作不可数名词。"
  },
  {
    id: "hs_require",
    text: "require",
    phonetic: "/rɪˈkwaɪə(r)/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "v.",
    meaning: "需要；要求",
    example: "The job requires patience and careful planning.",
    collocation: "require sb. to do sth.",
    note: "常用于说明规则、任务或条件。"
  },
  {
    id: "hs_strategy",
    text: "strategy",
    phonetic: "/ˈstrætədʒi/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n.",
    meaning: "策略；方法",
    example: "A good learning strategy can save time.",
    collocation: "learning strategy",
    note: "作文中可用来表达“解决问题的方法”。"
  },
  {
    id: "cet4_access",
    text: "access",
    phonetic: "/ˈækses/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n./v.",
    meaning: "进入权；使用机会；访问",
    example: "Students have access to the digital library.",
    collocation: "have access to",
    note: "to 是介词，后接名词或动名词。"
  },
  {
    id: "cet4_issue",
    text: "issue",
    phonetic: "/ˈɪʃuː/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n./v.",
    meaning: "问题；议题；发布",
    example: "The school issued a new safety notice.",
    collocation: "issue a statement",
    note: "名词是“议题”，动词是“发布”。"
  },
  {
    id: "cet4_factor",
    text: "factor",
    phonetic: "/ˈfæktə(r)/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "因素；要素",
    example: "Sleep is an important factor in learning efficiency.",
    collocation: "a key factor in",
    note: "作文和阅读中都很高频。"
  },
  {
    id: "cet6_compensate",
    text: "compensate",
    phonetic: "/ˈkɒmpenseɪt/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "v.",
    meaning: "补偿；弥补",
    example: "Extra practice can compensate for lost time.",
    collocation: "compensate for",
    note: "常和 for 搭配。"
  },
  {
    id: "cet_assumption",
    text: "assumption",
    phonetic: "/əˈsʌmpʃn/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "假设；设想",
    example: "The plan is based on a wrong assumption.",
    collocation: "make an assumption",
    note: "阅读中常用于论证和观点分析。"
  },
  {
    id: "cet_capacity",
    text: "capacity",
    phonetic: "/kəˈpæsəti/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "能力；容量",
    example: "The hall has a seating capacity of 500.",
    collocation: "capacity for",
    note: "既可指人的能力，也可指空间容量。"
  },
  {
    id: "cet_consequence",
    text: "consequence",
    phonetic: "/ˈkɒnsɪkwəns/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "结果；后果",
    example: "Every decision has its consequences.",
    collocation: "as a consequence",
    note: "常用于说明因果关系。"
  },
  {
    id: "cet_decline",
    text: "decline",
    phonetic: "/dɪˈklaɪn/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n./v.",
    meaning: "下降；拒绝",
    example: "The number of visitors declined last year.",
    collocation: "a decline in",
    note: "可表示数量下降，也可表示礼貌拒绝。"
  },
  {
    id: "cet_emerge",
    text: "emerge",
    phonetic: "/ɪˈmɜːdʒ/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "v.",
    meaning: "出现；浮现",
    example: "New problems may emerge during the project.",
    collocation: "emerge from",
    note: "常用于描述趋势、问题或事实出现。"
  },
  {
    id: "cet_maintain",
    text: "maintain",
    phonetic: "/meɪnˈteɪn/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "v.",
    meaning: "维持；保持；主张",
    example: "It is hard to maintain a healthy balance.",
    collocation: "maintain balance",
    note: "阅读里也可表示“坚持认为”。"
  }
];

const extraHighSchoolRows = [
  ["hs_absorb", "absorb", "/əbˈzɔːb/", "v.", "吸收；理解", "Plants absorb water from the soil.", "absorb water", "阅读中常见“吸收信息、吸收水分”两类用法。"],
  ["hs_achieve", "achieve", "/əˈtʃiːv/", "v.", "实现；取得", "She worked hard to achieve her goal.", "achieve a goal", "作文中常用于表达实现目标。"],
  ["hs_adapt", "adapt", "/əˈdæpt/", "v.", "适应；改编", "Students need time to adapt to a new school.", "adapt to", "adapt to 中的 to 是介词。"],
  ["hs_admit", "admit", "/ədˈmɪt/", "v.", "承认；允许进入", "He admitted that he had made a mistake.", "admit doing sth.", "后接动名词时表示承认做过某事。"],
  ["hs_affect", "affect", "/əˈfekt/", "v.", "影响", "Sleep can affect your memory and attention.", "affect one's health", "注意和 effect 区分，affect 通常作动词。"],
  ["hs_afford", "afford", "/əˈfɔːd/", "v.", "负担得起；抽得出", "Many students cannot afford to waste time.", "afford to do sth.", "常用于否定句或 can/could 后。"],
  ["hs_aim", "aim", "/eɪm/", "n./v.", "目标；旨在", "The program aims to improve reading skills.", "aim to do sth.", "既可作名词“目标”，也可作动词“旨在”。"],
  ["hs_appeal", "appeal", "/əˈpiːl/", "n./v.", "吸引力；呼吁", "The story has a strong appeal to teenagers.", "appeal to", "appeal to 可表示“吸引”或“呼吁”。"],
  ["hs_arrange", "arrange", "/əˈreɪndʒ/", "v.", "安排；整理", "The teacher arranged a meeting after class.", "arrange a meeting", "常用于安排活动、时间和座位。"],
  ["hs_attempt", "attempt", "/əˈtempt/", "n./v.", "尝试；企图", "They made an attempt to solve the problem.", "make an attempt to do sth.", "比 try 更正式，阅读中高频。"],
  ["hs_attitude", "attitude", "/ˈætɪtjuːd/", "n.", "态度；看法", "A positive attitude helps students face challenges.", "attitude toward", "常和 toward/to 搭配。"],
  ["hs_audience", "audience", "/ˈɔːdiəns/", "n.", "观众；听众", "The audience listened carefully to the speech.", "target audience", "作文和阅读中可指目标读者。"],
  ["hs_balance", "balance", "/ˈbæləns/", "n./v.", "平衡；权衡", "It is important to balance study and rest.", "keep a balance", "常用于学习、生活、工作之间的平衡。"],
  ["hs_behavior", "behavior", "/bɪˈheɪvjə(r)/", "n.", "行为；表现", "Good behavior is expected in the classroom.", "student behavior", "不可数时表示整体行为表现。"],
  ["hs_career", "career", "/kəˈrɪə(r)/", "n.", "职业；事业", "He hopes to start a career in medicine.", "career plan", "不要只理解为“工作”，也指长期职业发展。"],
  ["hs_combine", "combine", "/kəmˈbaɪn/", "v.", "结合；联合", "The course combines theory with practice.", "combine A with B", "常用于说明两种事物结合。"],
  ["hs_comment", "comment", "/ˈkɒment/", "n./v.", "评论；发表意见", "The article received many positive comments.", "comment on", "comment on 表示“评论……”。"],
  ["hs_communicate", "communicate", "/kəˈmjuːnɪkeɪt/", "v.", "交流；传达", "Good friends communicate honestly with each other.", "communicate with", "强调信息或情感的交流。"],
  ["hs_compare", "compare", "/kəmˈpeə(r)/", "v.", "比较；比作", "We compared the two methods carefully.", "compare A with B", "compare with 强调比较，compare to 可表示比作。"],
  ["hs_compete", "compete", "/kəmˈpiːt/", "v.", "竞争；比赛", "Students compete for a place in the final.", "compete with", "名词 competition，形容词 competitive。"],
  ["hs_concentrate", "concentrate", "/ˈkɒnsntreɪt/", "v.", "集中注意力", "It is hard to concentrate in a noisy room.", "concentrate on", "on 后接名词或动名词。"],
  ["hs_conclude", "conclude", "/kənˈkluːd/", "v.", "得出结论；结束", "We concluded that the plan was practical.", "conclude that", "阅读中常用于实验或调查结论。"],
  ["hs_conduct", "conduct", "/kənˈdʌkt/", "v./n.", "实施；行为", "The students conducted a survey on reading habits.", "conduct a survey", "作动词时常表示开展调查、实验。"],
  ["hs_confident", "confident", "/ˈkɒnfɪdənt/", "adj.", "自信的；有把握的", "She is confident about the coming exam.", "be confident about", "名词 confidence。"],
  ["hs_consider", "consider", "/kənˈsɪdə(r)/", "v.", "考虑；认为", "You should consider joining the reading club.", "consider doing sth.", "consider 后接动名词，不接 to do。"],
  ["hs_contribute", "contribute", "/kənˈtrɪbjuːt/", "v.", "贡献；导致", "Everyone can contribute to protecting the environment.", "contribute to", "to 是介词，后接名词或动名词。"],
  ["hs_convenient", "convenient", "/kənˈviːniənt/", "adj.", "方便的", "Online learning is convenient for many students.", "be convenient for", "主语通常是事物，不说 people are convenient。"],
  ["hs_creative", "creative", "/kriˈeɪtɪv/", "adj.", "有创造力的", "Creative thinking is useful in problem solving.", "creative thinking", "写作中可用于描述能力和方法。"],
  ["hs_culture", "culture", "/ˈkʌltʃə(r)/", "n.", "文化", "Learning a language also means learning its culture.", "traditional culture", "作文中高频，可和 traditional 搭配。"],
  ["hs_curious", "curious", "/ˈkjʊəriəs/", "adj.", "好奇的", "Children are naturally curious about the world.", "be curious about", "curiosity 是名词。"],
  ["hs_debate", "debate", "/dɪˈbeɪt/", "n./v.", "辩论；讨论", "The class held a debate on school uniforms.", "a debate on", "比 discussion 更强调正反观点。"],
  ["hs_decision", "decision", "/dɪˈsɪʒn/", "n.", "决定", "Making a wise decision is not always easy.", "make a decision", "动词是 decide。"],
  ["hs_decrease", "decrease", "/dɪˈkriːs/", "v./n.", "减少；下降", "The number of visitors decreased in winter.", "a decrease in", "和 increase 相反，常考图表表达。"],
  ["hs_demand", "demand", "/dɪˈmɑːnd/", "n./v.", "需求；要求", "There is a growing demand for clean energy.", "demand for", "可作名词“需求”，也可作动词“要求”。"],
  ["hs_describe", "describe", "/dɪˈskraɪb/", "v.", "描述", "The writer describes the village in great detail.", "describe sth. as", "名词 description。"],
  ["hs_determine", "determine", "/dɪˈtɜːmɪn/", "v.", "决定；确定", "Your attitude may determine your success.", "determine whether", "形容词 determined 表示有决心的。"],
  ["hs_develop", "develop", "/dɪˈveləp/", "v.", "发展；培养", "Students should develop good reading habits.", "develop a habit", "常用于能力、习惯、经济的发展。"],
  ["hs_differ", "differ", "/ˈdɪfə(r)/", "v.", "不同；有区别", "People differ in their learning styles.", "differ from", "名词 difference，形容词 different。"],
  ["hs_disaster", "disaster", "/dɪˈzɑːstə(r)/", "n.", "灾难；灾害", "The flood was a serious natural disaster.", "natural disaster", "常用于自然灾害类阅读。"],
  ["hs_economy", "economy", "/ɪˈkɒnəmi/", "n.", "经济", "Tourism plays an important role in the local economy.", "local economy", "economic 是形容词“经济的”。"],
  ["hs_educate", "educate", "/ˈedʒukeɪt/", "v.", "教育；培养", "Parents and schools should educate children together.", "educate sb. to do sth.", "名词 education，形容词 educational。"],
  ["hs_effort", "effort", "/ˈefət/", "n.", "努力", "Success requires time and effort.", "make an effort", "常用于作文表达努力。"],
  ["hs_encourage", "encourage", "/ɪnˈkʌrɪdʒ/", "v.", "鼓励；促进", "Teachers encourage students to ask questions.", "encourage sb. to do sth.", "反义 discourage。"],
  ["hs_environment", "environment", "/ɪnˈvaɪrənmənt/", "n.", "环境", "A quiet environment helps students study better.", "protect the environment", "自然环境和学习环境都可用。"],
  ["hs_establish", "establish", "/ɪˈstæblɪʃ/", "v.", "建立；确立", "The school established a new reading club.", "establish a system", "比 build 更正式。"],
  ["hs_exchange", "exchange", "/ɪksˈtʃeɪndʒ/", "n./v.", "交换；交流", "Students can exchange ideas after class.", "exchange ideas", "也可指交换生 exchange student。"],
  ["hs_experience", "experience", "/ɪkˈspɪəriəns/", "n./v.", "经历；经验；体验", "The trip was a valuable learning experience.", "gain experience", "作“经验”时常不可数，作“经历”时可数。"],
  ["hs_expert", "expert", "/ˈekspɜːt/", "n./adj.", "专家；熟练的", "Experts suggest that teenagers should sleep enough.", "an expert in", "名词专家，形容词熟练的。"],
  ["hs_express", "express", "/ɪkˈspres/", "v.", "表达；表示", "Writing helps students express their thoughts clearly.", "express one's opinion", "名词 expression。"],
  ["hs_figure", "figure", "/ˈfɪɡə(r)/", "n./v.", "数字；人物；认为", "The latest figures show a rise in online reading.", "figure out", "figure out 表示弄明白。"],
  ["hs_focus", "focus", "/ˈfəʊkəs/", "n./v.", "焦点；集中", "The lesson focuses on reading strategies.", "focus on", "on 后接名词或动名词。"],
  ["hs_function", "function", "/ˈfʌŋkʃn/", "n./v.", "功能；起作用", "The app has a useful review function.", "main function", "作动词时表示发挥作用。"],
  ["hs_generation", "generation", "/ˌdʒenəˈreɪʃn/", "n.", "一代人；产生", "Each generation has its own way of learning.", "younger generation", "常用于社会变化类阅读。"],
  ["hs_global", "global", "/ˈɡləʊbl/", "adj.", "全球的；全局的", "Climate change is a global problem.", "global problem", "名词 globe。"],
  ["hs_graduate", "graduate", "/ˈɡrædʒueɪt/", "v./n.", "毕业；毕业生", "She will graduate from high school next year.", "graduate from", "作动词时重音常在前或后，注意搭配 from。"],
  ["hs_habit", "habit", "/ˈhæbɪt/", "n.", "习惯", "Good habits are built through daily practice.", "form a habit", "常和 good/bad 搭配。"],
  ["hs_hesitate", "hesitate", "/ˈhezɪteɪt/", "v.", "犹豫", "Do not hesitate to ask for help.", "hesitate to do sth.", "常用于礼貌表达。"],
  ["hs_identify", "identify", "/aɪˈdentɪfaɪ/", "v.", "识别；确认", "The study identified several causes of stress.", "identify a problem", "阅读中常表示找出原因、问题。"],
  ["hs_ignore", "ignore", "/ɪɡˈnɔː(r)/", "v.", "忽视；不理会", "We should not ignore small problems.", "ignore advice", "常用于说明忽视风险或建议。"],
  ["hs_impact", "impact", "/ˈɪmpækt/", "n./v.", "影响；冲击", "Technology has a strong impact on education.", "have an impact on", "名词搭配非常高频。"],
  ["hs_improve", "improve", "/ɪmˈpruːv/", "v.", "改善；提高", "Practice can improve your spoken English.", "improve skills", "名词 improvement。"],
  ["hs_include", "include", "/ɪnˈkluːd/", "v.", "包括；包含", "The activities include reading and discussion.", "include doing sth.", "including 是介词，后接名词或动名词。"],
  ["hs_independent", "independent", "/ˌɪndɪˈpendənt/", "adj.", "独立的", "Teenagers should learn to be independent.", "be independent of", "名词 independence。"],
  ["hs_influence", "influence", "/ˈɪnfluəns/", "n./v.", "影响", "Parents have a great influence on children.", "have an influence on", "名词和动词都高频。"],
  ["hs_inspire", "inspire", "/ɪnˈspaɪə(r)/", "v.", "激励；启发", "The story inspired many students to keep trying.", "inspire sb. to do sth.", "常用于人物故事类阅读。"],
  ["hs_involve", "involve", "/ɪnˈvɒlv/", "v.", "涉及；包含", "The project involves collecting data from students.", "involve doing sth.", "后接动名词。"],
  ["hs_judge", "judge", "/dʒʌdʒ/", "v./n.", "判断；法官；裁判", "Do not judge a person only by appearance.", "judge by", "既可作动词也可作名词。"],
  ["hs_knowledge", "knowledge", "/ˈnɒlɪdʒ/", "n.", "知识", "Reading is a good way to gain knowledge.", "gain knowledge", "通常不可数。"],
  ["hs_lack", "lack", "/læk/", "n./v.", "缺乏", "Many students lack confidence in speaking English.", "lack confidence", "作动词时不加 of，作名词常用 lack of。"],
  ["hs_limit", "limit", "/ˈlɪmɪt/", "n./v.", "限制；限度", "Screen time should be limited during school days.", "limit time", "名词 limitation。"],
  ["hs_manage", "manage", "/ˈmænɪdʒ/", "v.", "管理；设法做到", "She managed to finish the task on time.", "manage to do sth.", "manage to do 表示成功做成。"],
  ["hs_measure", "measure", "/ˈmeʒə(r)/", "n./v.", "措施；测量", "The school took measures to improve safety.", "take measures", "作名词“措施”时常用复数。"],
  ["hs_method", "method", "/ˈmeθəd/", "n.", "方法", "This method can help students remember words.", "learning method", "比 way 更正式。"],
  ["hs_opportunity", "opportunity", "/ˌɒpəˈtjuːnəti/", "n.", "机会", "The competition gives students an opportunity to grow.", "an opportunity to do sth.", "作文中常用于表达机会。"],
  ["hs_organize", "organize", "/ˈɔːɡənaɪz/", "v.", "组织；安排", "Students organized a charity sale last weekend.", "organize an activity", "名词 organization。"],
  ["hs_participate", "participate", "/pɑːˈtɪsɪpeɪt/", "v.", "参加；参与", "More students are encouraged to participate in sports.", "participate in", "比 join in 更正式。"],
  ["hs_perform", "perform", "/pəˈfɔːm/", "v.", "表演；表现；执行", "The students performed well in the final exam.", "perform well", "performance 是名词。"],
  ["hs_personal", "personal", "/ˈpɜːsənl/", "adj.", "个人的；私人的", "Everyone has a personal learning style.", "personal information", "注意和 personnel 区分。"],
  ["hs_persuade", "persuade", "/pəˈsweɪd/", "v.", "说服", "He persuaded his friend to join the club.", "persuade sb. to do sth.", "强调成功说服。"],
  ["hs_positive", "positive", "/ˈpɒzətɪv/", "adj.", "积极的；肯定的", "A positive attitude can make a difference.", "positive attitude", "反义 negative。"],
  ["hs_pressure", "pressure", "/ˈpreʃə(r)/", "n.", "压力", "Students often feel pressure before exams.", "under pressure", "常用于学习压力话题。"],
  ["hs_prevent", "prevent", "/prɪˈvent/", "v.", "阻止；预防", "Exercise can prevent some health problems.", "prevent sb. from doing sth.", "from 可省略，但考试中常保留。"],
  ["hs_process", "process", "/ˈprəʊses/", "n./v.", "过程；处理", "Learning a language is a long process.", "learning process", "名词“过程”很高频。"],
  ["hs_promote", "promote", "/prəˈməʊt/", "v.", "促进；推广", "Reading can promote independent thinking.", "promote development", "常用于积极影响。"],
  ["hs_protect", "protect", "/prəˈtekt/", "v.", "保护", "We should protect wild animals and forests.", "protect...from", "名词 protection。"],
  ["hs_purpose", "purpose", "/ˈpɜːpəs/", "n.", "目的；意图", "The purpose of the activity is to raise awareness.", "the purpose of", "常用于阅读主旨题。"],
  ["hs_recommend", "recommend", "/ˌrekəˈmend/", "v.", "推荐；建议", "The teacher recommended this book to us.", "recommend sth. to sb.", "也可接 doing 或 that 从句。"],
  ["hs_reduce", "reduce", "/rɪˈdjuːs/", "v.", "减少；降低", "Walking to school can reduce pollution.", "reduce stress", "反义 increase。"],
  ["hs_reflect", "reflect", "/rɪˈflekt/", "v.", "反映；反思", "The story reflects the writer's childhood experience.", "reflect on", "reflect on 表示认真思考。"],
  ["hs_relationship", "relationship", "/rɪˈleɪʃnʃɪp/", "n.", "关系", "A good relationship between teachers and students matters.", "relationship between", "常用于人与人、事物之间的关系。"]
];

const extraHighSchoolWords = extraHighSchoolRows.map((row) => ({
  id: row[0],
  text: row[1],
  phonetic: row[2],
  level: "high_school",
  book: "高中核心",
  partOfSpeech: row[3],
  meaning: row[4],
  example: row[5],
  collocation: row[6],
  note: row[7]
}));

const allWords = [...words, ...extraHighSchoolWords];

const books = [
  {
    id: "elementary",
    name: "小学",
    description: "基础词汇和常见生活表达，适合打底和低压力练习。"
  },
  {
    id: "high_school",
    name: "高中",
    description: "高考阅读、完形和写作中最应该稳住的词。"
  },
  {
    id: "cet",
    name: "四六级",
    description: "适合词汇量较好的学生提前拓展，偏阅读和写作高频词。"
  }
];

module.exports = {
  words: allWords,
  books
};
