const words = [
  {
    id: "el_animal",
    text: "animal",
    phonetic: "/ˈænɪml/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "n.",
    meaning: "动物",
    example: "The panda is my favorite animal.",
    collocation: "wild animal",
    note: "小学常见名词，注意复数 animals。"
  },
  {
    id: "el_weather",
    text: "weather",
    phonetic: "/ˈweðə(r)/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "n.",
    meaning: "天气",
    example: "The weather is sunny today.",
    collocation: "good weather",
    note: "不可数名词，不说 a weather。"
  },
  {
    id: "el_library",
    text: "library",
    phonetic: "/ˈlaɪbrəri/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "n.",
    meaning: "图书馆",
    example: "I read books in the library.",
    collocation: "school library",
    note: "注意拼写，不要漏掉 r。"
  },
  {
    id: "el_important",
    text: "important",
    phonetic: "/ɪmˈpɔːtnt/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "adj.",
    meaning: "重要的",
    example: "English is an important subject.",
    collocation: "be important to",
    note: "常用于表达某事很重要。"
  },
  {
    id: "el_because",
    text: "because",
    phonetic: "/bɪˈkɒz/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "conj.",
    meaning: "因为",
    example: "I like English because it is useful.",
    collocation: "because of",
    note: "because 后接句子，because of 后接名词。"
  },
  {
    id: "el_careful",
    text: "careful",
    phonetic: "/ˈkeəfl/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "adj.",
    meaning: "仔细的；小心的",
    example: "Be careful when you cross the road.",
    collocation: "be careful with",
    note: "常用于提醒注意安全或细节。"
  },
  {
    id: "el_finish",
    text: "finish",
    phonetic: "/ˈfɪnɪʃ/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "v.",
    meaning: "完成；结束",
    example: "I finish my homework before dinner.",
    collocation: "finish doing sth.",
    note: "finish 后面接动词 ing 形式。"
  },
  {
    id: "el_healthy",
    text: "healthy",
    phonetic: "/ˈhelθi/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "adj.",
    meaning: "健康的",
    example: "Fruit and vegetables are healthy food.",
    collocation: "keep healthy",
    note: "注意 healthy 是形容词，health 是名词。"
  },
  {
    id: "el_question",
    text: "question",
    phonetic: "/ˈkwestʃən/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "n.",
    meaning: "问题",
    example: "Can I ask you a question?",
    collocation: "answer a question",
    note: "常和 ask、answer 搭配。"
  },
  {
    id: "el_together",
    text: "together",
    phonetic: "/təˈɡeðə(r)/",
    level: "elementary",
    book: "小学",
    partOfSpeech: "adv.",
    meaning: "一起",
    example: "We study together after school.",
    collocation: "work together",
    note: "表示共同做某事。"
  },
  {
    id: "hs_approach",
    text: "approach",
    phonetic: "/əˈprəʊtʃ/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "方法；接近；处理",
    example: "We need a new approach to solving this problem.",
    collocation: "an approach to doing sth.",
    note: "阅读中常考“方法、途径”，不只是“接近”。"
  },
  {
    id: "hs_concern",
    text: "concern",
    phonetic: "/kənˈsɜːn/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "担心；涉及；关心",
    example: "The report concerns the safety of students.",
    collocation: "be concerned about",
    note: "既可表示“担忧”，也可表示“涉及”。"
  },
  {
    id: "hs_available",
    text: "available",
    phonetic: "/əˈveɪləbl/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "adj.",
    meaning: "可获得的；有空的",
    example: "Tickets are available online.",
    collocation: "be available to sb.",
    note: "常用于资源、时间、服务是否可用。"
  },
  {
    id: "hs_account",
    text: "account",
    phonetic: "/əˈkaʊnt/",
    level: "high_school",
    book: "熟词生义",
    partOfSpeech: "n./v.",
    meaning: "账户；描述；解释；占比",
    example: "Students account for 60 percent of the visitors.",
    collocation: "account for",
    note: "account for 常考“解释”或“占……比例”。"
  },
  {
    id: "hs_analyze",
    text: "analyze",
    phonetic: "/ˈænəlaɪz/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "v.",
    meaning: "分析",
    example: "We need to analyze the reasons for the change.",
    collocation: "analyze a problem",
    note: "阅读和写作中常用于分析原因、数据和问题。"
  },
  {
    id: "hs_benefit",
    text: "benefit",
    phonetic: "/ˈbenɪfɪt/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "好处；使受益",
    example: "Reading benefits students in many ways.",
    collocation: "benefit from",
    note: "benefit from 表示“从……中受益”。"
  },
  {
    id: "hs_challenge",
    text: "challenge",
    phonetic: "/ˈtʃælɪndʒ/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n./v.",
    meaning: "挑战；质疑",
    example: "The new task is a real challenge for us.",
    collocation: "face a challenge",
    note: "既可作名词，也可作动词。"
  },
  {
    id: "hs_evidence",
    text: "evidence",
    phonetic: "/ˈevɪdəns/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n.",
    meaning: "证据",
    example: "There is clear evidence that exercise improves sleep.",
    collocation: "clear evidence",
    note: "通常作不可数名词。"
  },
  {
    id: "hs_require",
    text: "require",
    phonetic: "/rɪˈkwaɪə(r)/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "v.",
    meaning: "需要；要求",
    example: "The job requires patience and careful planning.",
    collocation: "require sb. to do sth.",
    note: "常用于说明规则、任务或条件。"
  },
  {
    id: "hs_strategy",
    text: "strategy",
    phonetic: "/ˈstrætədʒi/",
    level: "high_school",
    book: "高中核心",
    partOfSpeech: "n.",
    meaning: "策略；方法",
    example: "A good learning strategy can save time.",
    collocation: "learning strategy",
    note: "作文中可用来表达“解决问题的方法”。"
  },
  {
    id: "cet4_access",
    text: "access",
    phonetic: "/ˈækses/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n./v.",
    meaning: "进入权；使用机会；访问",
    example: "Students have access to the digital library.",
    collocation: "have access to",
    note: "to 是介词，后接名词或动名词。"
  },
  {
    id: "cet4_issue",
    text: "issue",
    phonetic: "/ˈɪʃuː/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n./v.",
    meaning: "问题；议题；发布",
    example: "The school issued a new safety notice.",
    collocation: "issue a statement",
    note: "名词是“议题”，动词是“发布”。"
  },
  {
    id: "cet4_factor",
    text: "factor",
    phonetic: "/ˈfæktə(r)/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "因素；要素",
    example: "Sleep is an important factor in learning efficiency.",
    collocation: "a key factor in",
    note: "作文和阅读中都很高频。"
  },
  {
    id: "cet6_compensate",
    text: "compensate",
    phonetic: "/ˈkɒmpenseɪt/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "v.",
    meaning: "补偿；弥补",
    example: "Extra practice can compensate for lost time.",
    collocation: "compensate for",
    note: "常和 for 搭配。"
  },
  {
    id: "cet_assumption",
    text: "assumption",
    phonetic: "/əˈsʌmpʃn/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "假设；设想",
    example: "The plan is based on a wrong assumption.",
    collocation: "make an assumption",
    note: "阅读中常用于论证和观点分析。"
  },
  {
    id: "cet_capacity",
    text: "capacity",
    phonetic: "/kəˈpæsəti/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "能力；容量",
    example: "The hall has a seating capacity of 500.",
    collocation: "capacity for",
    note: "既可指人的能力，也可指空间容量。"
  },
  {
    id: "cet_consequence",
    text: "consequence",
    phonetic: "/ˈkɒnsɪkwəns/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n.",
    meaning: "结果；后果",
    example: "Every decision has its consequences.",
    collocation: "as a consequence",
    note: "常用于说明因果关系。"
  },
  {
    id: "cet_decline",
    text: "decline",
    phonetic: "/dɪˈklaɪn/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "n./v.",
    meaning: "下降；拒绝",
    example: "The number of visitors declined last year.",
    collocation: "a decline in",
    note: "可表示数量下降，也可表示礼貌拒绝。"
  },
  {
    id: "cet_emerge",
    text: "emerge",
    phonetic: "/ɪˈmɜːdʒ/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "v.",
    meaning: "出现；浮现",
    example: "New problems may emerge during the project.",
    collocation: "emerge from",
    note: "常用于描述趋势、问题或事实出现。"
  },
  {
    id: "cet_maintain",
    text: "maintain",
    phonetic: "/meɪnˈteɪn/",
    level: "cet",
    book: "四六级拓展",
    partOfSpeech: "v.",
    meaning: "维持；保持；主张",
    example: "It is hard to maintain a healthy balance.",
    collocation: "maintain balance",
    note: "阅读里也可表示“坚持认为”。"
  }
];

const extraElementaryRows = [
  ["el_activity", "activity", "/ækˈtɪvəti/", "n.", "活动", "We have many activities after school.", "school activity", "小学常见校园生活词，注意复数 activities。"],
  ["el_airport", "airport", "/ˈeəpɔːt/", "n.", "机场", "My uncle works at the airport.", "at the airport", "由 air 和 port 组成，表示机场。"],
  ["el_always", "always", "/ˈɔːlweɪz/", "adv.", "总是；一直", "She always gets up early.", "always do sth.", "频度副词，通常放在实义动词前。"],
  ["el_autumn", "autumn", "/ˈɔːtəm/", "n.", "秋天", "The leaves turn yellow in autumn.", "in autumn", "英式常用 autumn，美式也常说 fall。"],
  ["el_basketball", "basketball", "/ˈbɑːskɪtbɔːl/", "n.", "篮球", "We play basketball on Friday afternoon.", "play basketball", "球类运动前通常不加 the。"],
  ["el_bedroom", "bedroom", "/ˈbedruːm/", "n.", "卧室", "There is a desk in my bedroom.", "my bedroom", "家庭房间类常用词。"],
  ["el_beside", "beside", "/bɪˈsaɪd/", "prep.", "在……旁边", "The chair is beside the bed.", "beside the door", "表示位置，和 besides 意思不同。"],
  ["el_borrow", "borrow", "/ˈbɒrəʊ/", "v.", "借入；借用", "Can I borrow your ruler?", "borrow sth. from sb.", "borrow 是借入，lend 是借出。"],
  ["el_breakfast", "breakfast", "/ˈbrekfəst/", "n.", "早餐", "I usually have bread for breakfast.", "have breakfast", "三餐前一般不加冠词。"],
  ["el_bridge", "bridge", "/brɪdʒ/", "n.", "桥", "There is a bridge over the river.", "over the bridge", "常用于地点描述。"],
  ["el_building", "building", "/ˈbɪldɪŋ/", "n.", "建筑物", "The library is a tall building.", "school building", "由 build 加 ing 构成名词。"],
  ["el_camera", "camera", "/ˈkæmərə/", "n.", "照相机；摄像头", "She takes photos with a camera.", "digital camera", "科技和生活场景常用词。"],
  ["el_cartoon", "cartoon", "/kɑːˈtuːn/", "n.", "动画片；漫画", "Children like watching cartoons.", "watch cartoons", "注意复数 cartoons。"],
  ["el_chocolate", "chocolate", "/ˈtʃɒklət/", "n.", "巧克力", "I bought some chocolate for my sister.", "a piece of chocolate", "作食物总称时常不可数。"],
  ["el_classmate", "classmate", "/ˈklɑːsmeɪt/", "n.", "同班同学", "Tom is my new classmate.", "my classmate", "由 class 和 mate 组成。"],
  ["el_clean", "clean", "/kliːn/", "v./adj.", "打扫；干净的", "We clean the classroom every day.", "clean the room", "既可作动词，也可作形容词。"],
  ["el_clothes", "clothes", "/kləʊðz/", "n.", "衣服", "Put your clothes in the box.", "wear clothes", "总是复数形式。"],
  ["el_collect", "collect", "/kəˈlekt/", "v.", "收集", "I like to collect stamps.", "collect stamps", "名词 collection。"],
  ["el_colorful", "colorful", "/ˈkʌləfl/", "adj.", "五颜六色的；丰富多彩的", "The flowers are colorful.", "colorful life", "美式拼写 colorful，英式 colourful。"],
  ["el_computer", "computer", "/kəmˈpjuːtə(r)/", "n.", "电脑", "We use a computer in the lesson.", "use a computer", "信息技术类基础词。"],
  ["el_countryside", "countryside", "/ˈkʌntrisaɪd/", "n.", "乡村；农村", "My grandparents live in the countryside.", "in the countryside", "常和 city 对比。"],
  ["el_delicious", "delicious", "/dɪˈlɪʃəs/", "adj.", "美味的", "The fish tastes delicious.", "delicious food", "常用于描述食物。"],
  ["el_difficult", "difficult", "/ˈdɪfɪkəlt/", "adj.", "困难的", "This question is difficult for me.", "be difficult for", "反义词 easy。"],
  ["el_dinner", "dinner", "/ˈdɪnə(r)/", "n.", "晚餐；正餐", "We have dinner at seven.", "have dinner", "三餐表达常考。"],
  ["el_direction", "direction", "/dəˈrekʃn/", "n.", "方向；指示", "Can you tell me the direction to the museum?", "in the direction of", "问路和位置类常用词。"],
  ["el_doctor", "doctor", "/ˈdɒktə(r)/", "n.", "医生", "The doctor is very kind.", "see a doctor", "看医生用 see a doctor。"],
  ["el_driver", "driver", "/ˈdraɪvə(r)/", "n.", "司机", "The bus driver is careful.", "bus driver", "由 drive 加 r 构成。"],
  ["el_during", "during", "/ˈdjʊərɪŋ/", "prep.", "在……期间", "I read books during the holiday.", "during the holiday", "后接一段时间。"],
  ["el_early", "early", "/ˈɜːli/", "adv./adj.", "早；早的", "I go to school early.", "get up early", "可作副词和形容词。"],
  ["el_elephant", "elephant", "/ˈelɪfənt/", "n.", "大象", "An elephant has a long nose.", "an elephant", "以元音音素开头，用 an。"],
  ["el_email", "email", "/ˈiːmeɪl/", "n./v.", "电子邮件；发邮件", "Please send me an email.", "send an email", "也可写作 e-mail。"],
  ["el_exercise", "exercise", "/ˈeksəsaɪz/", "n./v.", "练习；锻炼", "Doing exercise is good for health.", "do exercise", "可表示运动，也可表示练习题。"],
  ["el_festival", "festival", "/ˈfestɪvl/", "n.", "节日", "The Spring Festival is my favorite festival.", "traditional festival", "节日类高频词。"],
  ["el_flower", "flower", "/ˈflaʊə(r)/", "n.", "花", "There are many flowers in the park.", "beautiful flower", "注意复数 flowers。"],
  ["el_forest", "forest", "/ˈfɒrɪst/", "n.", "森林", "Many animals live in the forest.", "in the forest", "自然环境类常用词。"],
  ["el_friendly", "friendly", "/ˈfrendli/", "adj.", "友好的", "Our English teacher is friendly.", "be friendly to", "虽然以 ly 结尾，但 friendly 是形容词。"],
  ["el_future", "future", "/ˈfjuːtʃə(r)/", "n./adj.", "未来；将来的", "I want to be a teacher in the future.", "in the future", "常用于理想和计划。"],
  ["el_garden", "garden", "/ˈɡɑːdn/", "n.", "花园", "There are vegetables in the garden.", "in the garden", "家庭和地点类词。"],
  ["el_geography", "geography", "/dʒiˈɒɡrəfi/", "n.", "地理", "Geography helps us learn about the world.", "geography class", "学科类词，首字母不必大写。"],
  ["el_grandparent", "grandparent", "/ˈɡrænpeərənt/", "n.", "祖父或祖母；外祖父或外祖母", "I visit my grandparents every weekend.", "grandparents' home", "常用复数 grandparents。"],
  ["el_holiday", "holiday", "/ˈhɒlədeɪ/", "n.", "假期；节日", "We went to Beijing during the holiday.", "summer holiday", "英式常指假期。"],
  ["el_hospital", "hospital", "/ˈhɒspɪtl/", "n.", "医院", "My mother works in a hospital.", "go to hospital", "地点类基础词。"],
  ["el_hotel", "hotel", "/həʊˈtel/", "n.", "旅馆；酒店", "We stayed in a hotel near the lake.", "stay in a hotel", "旅游场景常用。"],
  ["el_housework", "housework", "/ˈhaʊswɜːk/", "n.", "家务", "I help my parents do housework.", "do housework", "不可数名词。"],
  ["el_interesting", "interesting", "/ˈɪntrəstɪŋ/", "adj.", "有趣的", "This book is very interesting.", "interesting story", "形容事物有趣用 interesting。"],
  ["el_invite", "invite", "/ɪnˈvaɪt/", "v.", "邀请", "I want to invite you to my birthday party.", "invite sb. to", "名词 invitation。"],
  ["el_kitchen", "kitchen", "/ˈkɪtʃɪn/", "n.", "厨房", "My father is cooking in the kitchen.", "in the kitchen", "家庭房间类词。"],
  ["el_lesson", "lesson", "/ˈlesn/", "n.", "课；教训", "We have an English lesson on Monday.", "English lesson", "可表示课程，也可表示教训。"],
  ["el_market", "market", "/ˈmɑːkɪt/", "n.", "市场；集市", "My grandma buys vegetables at the market.", "at the market", "生活场景词。"],
  ["el_mountain", "mountain", "/ˈmaʊntən/", "n.", "山；高山", "There is a high mountain near the village.", "climb a mountain", "自然地理类常见词。"],
  ["el_museum", "museum", "/mjuˈziːəm/", "n.", "博物馆", "We visited a science museum.", "visit a museum", "旅游和学习场景高频。"],
  ["el_newspaper", "newspaper", "/ˈnjuːzpeɪpə(r)/", "n.", "报纸", "My grandfather reads a newspaper every morning.", "read a newspaper", "由 news 和 paper 组成。"],
  ["el_notebook", "notebook", "/ˈnəʊtbʊk/", "n.", "笔记本", "Write the new words in your notebook.", "English notebook", "学习用品类词。"],
  ["el_often", "often", "/ˈɒfn/", "adv.", "经常", "I often play football after school.", "often do sth.", "频度副词，常用于一般现在时。"],
  ["el_palace", "palace", "/ˈpæləs/", "n.", "宫殿", "The Palace Museum is in Beijing.", "the Palace Museum", "旅游和中国文化场景常见。"],
  ["el_parent", "parent", "/ˈpeərənt/", "n.", "父亲或母亲", "Parents care about their children's study.", "parent meeting", "常用复数 parents 表示父母。"],
  ["el_picnic", "picnic", "/ˈpɪknɪk/", "n.", "野餐", "We will have a picnic in the park.", "have a picnic", "固定搭配 have a picnic。"],
  ["el_picture", "picture", "/ˈpɪktʃə(r)/", "n.", "图片；照片", "Look at the picture on the wall.", "take a picture", "也可表示照片。"],
  ["el_planet", "planet", "/ˈplænɪt/", "n.", "行星", "The earth is a planet.", "blue planet", "科学类基础词。"],
  ["el_playground", "playground", "/ˈpleɪɡraʊnd/", "n.", "操场", "Students run on the playground.", "on the playground", "校园场景常用。"],
  ["el_popular", "popular", "/ˈpɒpjələ(r)/", "adj.", "受欢迎的；流行的", "Basketball is popular in our school.", "be popular with", "with 后接人群。"],
  ["el_practice", "practice", "/ˈpræktɪs/", "n./v.", "练习；实践", "We practice speaking English every day.", "practice doing sth.", "后接动词 ing 形式。"],
  ["el_present", "present", "/ˈpreznt/", "n./adj.", "礼物；现在的；出席的", "I made a present for my friend.", "birthday present", "小学阶段常考“礼物”。"],
  ["el_program", "program", "/ˈprəʊɡræm/", "n.", "节目；程序", "This TV program is about animals.", "TV program", "美式拼写 program。"],
  ["el_protect", "protect", "/prəˈtekt/", "v.", "保护", "We should protect the earth.", "protect the environment", "环保主题常用词。"],
  ["el_quiet", "quiet", "/ˈkwaɪət/", "adj.", "安静的", "Please be quiet in the library.", "keep quiet", "注意和 quite 区分。"],
  ["el_raincoat", "raincoat", "/ˈreɪnkəʊt/", "n.", "雨衣", "Take your raincoat. It may rain.", "wear a raincoat", "由 rain 和 coat 组成。"],
  ["el_restaurant", "restaurant", "/ˈrestrɒnt/", "n.", "餐馆", "We had lunch in a restaurant.", "Chinese restaurant", "注意拼写中 au。"],
  ["el_river", "river", "/ˈrɪvə(r)/", "n.", "河流", "There is a long river near my home.", "along the river", "自然地理类基础词。"],
  ["el_science", "science", "/ˈsaɪəns/", "n.", "科学", "Science is my favorite subject.", "science class", "学科类常用词。"],
  ["el_season", "season", "/ˈsiːzn/", "n.", "季节", "Spring is my favorite season.", "four seasons", "四季表达高频。"],
  ["el_sometimes", "sometimes", "/ˈsʌmtaɪmz/", "adv.", "有时", "I sometimes ride a bike to school.", "sometimes do sth.", "频度副词。"],
  ["el_special", "special", "/ˈspeʃl/", "adj.", "特别的；特殊的", "Today is a special day for our class.", "special gift", "常用于描述日子、礼物、活动。"],
  ["el_stadium", "stadium", "/ˈsteɪdiəm/", "n.", "体育场", "The football match is in the stadium.", "sports stadium", "体育场景词。"],
  ["el_station", "station", "/ˈsteɪʃn/", "n.", "车站；站", "The train station is near the hotel.", "train station", "交通场景常用。"],
  ["el_straight", "straight", "/streɪt/", "adv./adj.", "笔直地；直的", "Go straight and turn left.", "go straight", "问路表达中很常用。"],
  ["el_study", "study", "/ˈstʌdi/", "v./n.", "学习；书房", "I study English every evening.", "study hard", "既可作动词也可作名词。"],
  ["el_subject", "subject", "/ˈsʌbdʒɪkt/", "n.", "学科；主题", "Maths is an interesting subject.", "school subject", "学科和话题都可用。"],
  ["el_suddenly", "suddenly", "/ˈsʌdənli/", "adv.", "突然", "Suddenly, it began to rain.", "suddenly happen", "故事叙述中常用。"],
  ["el_supermarket", "supermarket", "/ˈsuːpəmɑːkɪt/", "n.", "超市", "My mother buys fruit in the supermarket.", "go to the supermarket", "生活场景高频词。"],
  ["el_sweater", "sweater", "/ˈswetə(r)/", "n.", "毛衣", "I wear a sweater in winter.", "wear a sweater", "衣物类常用词。"],
  ["el_tomorrow", "tomorrow", "/təˈmɒrəʊ/", "n./adv.", "明天", "We will visit the museum tomorrow.", "tomorrow morning", "常用于一般将来时。"],
  ["el_traffic", "traffic", "/ˈtræfɪk/", "n.", "交通；车辆", "There is heavy traffic in the morning.", "traffic lights", "通常不可数。"],
  ["el_travel", "travel", "/ˈtrævl/", "v./n.", "旅行", "We travel to Shanghai by train.", "travel by train", "交通和假期话题常用。"],
  ["el_vegetable", "vegetable", "/ˈvedʒtəbl/", "n.", "蔬菜", "Carrots and potatoes are vegetables.", "fresh vegetables", "注意复数 vegetables。"],
  ["el_village", "village", "/ˈvɪlɪdʒ/", "n.", "村庄", "My grandparents live in a small village.", "small village", "常和 city、town 对比。"],
  ["el_visit", "visit", "/ˈvɪzɪt/", "v./n.", "参观；拜访", "We visit our grandparents on Sunday.", "visit a museum", "既可拜访人，也可参观地点。"],
  ["el_weekend", "weekend", "/ˌwiːkˈend/", "n.", "周末", "What do you do on the weekend?", "on the weekend", "英式常说 at the weekend。"],
  ["el_wonderful", "wonderful", "/ˈwʌndəfl/", "adj.", "精彩的；极好的", "We had a wonderful time at the party.", "wonderful time", "常用于表达积极感受。"],
  ["el_yesterday", "yesterday", "/ˈjestədeɪ/", "n./adv.", "昨天", "I watched a film yesterday.", "yesterday afternoon", "常用于一般过去时。"]
];

const extraElementaryWords = extraElementaryRows.map((row) => ({
  id: row[0],
  text: row[1],
  phonetic: row[2],
  level: "elementary",
  book: "小学",
  partOfSpeech: row[3],
  meaning: row[4],
  example: row[5],
  collocation: row[6],
  note: row[7]
}));

const extraHighSchoolRows = [
  ["hs_absorb", "absorb", "/əbˈzɔːb/", "v.", "吸收；理解", "Plants absorb water from the soil.", "absorb water", "阅读中常见“吸收信息、吸收水分”两类用法。"],
  ["hs_achieve", "achieve", "/əˈtʃiːv/", "v.", "实现；取得", "She worked hard to achieve her goal.", "achieve a goal", "作文中常用于表达实现目标。"],
  ["hs_adapt", "adapt", "/əˈdæpt/", "v.", "适应；改编", "Students need time to adapt to a new school.", "adapt to", "adapt to 中的 to 是介词。"],
  ["hs_admit", "admit", "/ədˈmɪt/", "v.", "承认；允许进入", "He admitted that he had made a mistake.", "admit doing sth.", "后接动名词时表示承认做过某事。"],
  ["hs_affect", "affect", "/əˈfekt/", "v.", "影响", "Sleep can affect your memory and attention.", "affect one's health", "注意和 effect 区分，affect 通常作动词。"],
  ["hs_afford", "afford", "/əˈfɔːd/", "v.", "负担得起；抽得出", "Many students cannot afford to waste time.", "afford to do sth.", "常用于否定句或 can/could 后。"],
  ["hs_aim", "aim", "/eɪm/", "n./v.", "目标；旨在", "The program aims to improve reading skills.", "aim to do sth.", "既可作名词“目标”，也可作动词“旨在”。"],
  ["hs_appeal", "appeal", "/əˈpiːl/", "n./v.", "吸引力；呼吁", "The story has a strong appeal to teenagers.", "appeal to", "appeal to 可表示“吸引”或“呼吁”。"],
  ["hs_arrange", "arrange", "/əˈreɪndʒ/", "v.", "安排；整理", "The teacher arranged a meeting after class.", "arrange a meeting", "常用于安排活动、时间和座位。"],
  ["hs_attempt", "attempt", "/əˈtempt/", "n./v.", "尝试；企图", "They made an attempt to solve the problem.", "make an attempt to do sth.", "比 try 更正式，阅读中高频。"],
  ["hs_attitude", "attitude", "/ˈætɪtjuːd/", "n.", "态度；看法", "A positive attitude helps students face challenges.", "attitude toward", "常和 toward/to 搭配。"],
  ["hs_audience", "audience", "/ˈɔːdiəns/", "n.", "观众；听众", "The audience listened carefully to the speech.", "target audience", "作文和阅读中可指目标读者。"],
  ["hs_balance", "balance", "/ˈbæləns/", "n./v.", "平衡；权衡", "It is important to balance study and rest.", "keep a balance", "常用于学习、生活、工作之间的平衡。"],
  ["hs_behavior", "behavior", "/bɪˈheɪvjə(r)/", "n.", "行为；表现", "Good behavior is expected in the classroom.", "student behavior", "不可数时表示整体行为表现。"],
  ["hs_career", "career", "/kəˈrɪə(r)/", "n.", "职业；事业", "He hopes to start a career in medicine.", "career plan", "不要只理解为“工作”，也指长期职业发展。"],
  ["hs_combine", "combine", "/kəmˈbaɪn/", "v.", "结合；联合", "The course combines theory with practice.", "combine A with B", "常用于说明两种事物结合。"],
  ["hs_comment", "comment", "/ˈkɒment/", "n./v.", "评论；发表意见", "The article received many positive comments.", "comment on", "comment on 表示“评论……”。"],
  ["hs_communicate", "communicate", "/kəˈmjuːnɪkeɪt/", "v.", "交流；传达", "Good friends communicate honestly with each other.", "communicate with", "强调信息或情感的交流。"],
  ["hs_compare", "compare", "/kəmˈpeə(r)/", "v.", "比较；比作", "We compared the two methods carefully.", "compare A with B", "compare with 强调比较，compare to 可表示比作。"],
  ["hs_compete", "compete", "/kəmˈpiːt/", "v.", "竞争；比赛", "Students compete for a place in the final.", "compete with", "名词 competition，形容词 competitive。"],
  ["hs_concentrate", "concentrate", "/ˈkɒnsntreɪt/", "v.", "集中注意力", "It is hard to concentrate in a noisy room.", "concentrate on", "on 后接名词或动名词。"],
  ["hs_conclude", "conclude", "/kənˈkluːd/", "v.", "得出结论；结束", "We concluded that the plan was practical.", "conclude that", "阅读中常用于实验或调查结论。"],
  ["hs_conduct", "conduct", "/kənˈdʌkt/", "v./n.", "实施；行为", "The students conducted a survey on reading habits.", "conduct a survey", "作动词时常表示开展调查、实验。"],
  ["hs_confident", "confident", "/ˈkɒnfɪdənt/", "adj.", "自信的；有把握的", "She is confident about the coming exam.", "be confident about", "名词 confidence。"],
  ["hs_consider", "consider", "/kənˈsɪdə(r)/", "v.", "考虑；认为", "You should consider joining the reading club.", "consider doing sth.", "consider 后接动名词，不接 to do。"],
  ["hs_contribute", "contribute", "/kənˈtrɪbjuːt/", "v.", "贡献；导致", "Everyone can contribute to protecting the environment.", "contribute to", "to 是介词，后接名词或动名词。"],
  ["hs_convenient", "convenient", "/kənˈviːniənt/", "adj.", "方便的", "Online learning is convenient for many students.", "be convenient for", "主语通常是事物，不说 people are convenient。"],
  ["hs_creative", "creative", "/kriˈeɪtɪv/", "adj.", "有创造力的", "Creative thinking is useful in problem solving.", "creative thinking", "写作中可用于描述能力和方法。"],
  ["hs_culture", "culture", "/ˈkʌltʃə(r)/", "n.", "文化", "Learning a language also means learning its culture.", "traditional culture", "作文中高频，可和 traditional 搭配。"],
  ["hs_curious", "curious", "/ˈkjʊəriəs/", "adj.", "好奇的", "Children are naturally curious about the world.", "be curious about", "curiosity 是名词。"],
  ["hs_debate", "debate", "/dɪˈbeɪt/", "n./v.", "辩论；讨论", "The class held a debate on school uniforms.", "a debate on", "比 discussion 更强调正反观点。"],
  ["hs_decision", "decision", "/dɪˈsɪʒn/", "n.", "决定", "Making a wise decision is not always easy.", "make a decision", "动词是 decide。"],
  ["hs_decrease", "decrease", "/dɪˈkriːs/", "v./n.", "减少；下降", "The number of visitors decreased in winter.", "a decrease in", "和 increase 相反，常考图表表达。"],
  ["hs_demand", "demand", "/dɪˈmɑːnd/", "n./v.", "需求；要求", "There is a growing demand for clean energy.", "demand for", "可作名词“需求”，也可作动词“要求”。"],
  ["hs_describe", "describe", "/dɪˈskraɪb/", "v.", "描述", "The writer describes the village in great detail.", "describe sth. as", "名词 description。"],
  ["hs_determine", "determine", "/dɪˈtɜːmɪn/", "v.", "决定；确定", "Your attitude may determine your success.", "determine whether", "形容词 determined 表示有决心的。"],
  ["hs_develop", "develop", "/dɪˈveləp/", "v.", "发展；培养", "Students should develop good reading habits.", "develop a habit", "常用于能力、习惯、经济的发展。"],
  ["hs_differ", "differ", "/ˈdɪfə(r)/", "v.", "不同；有区别", "People differ in their learning styles.", "differ from", "名词 difference，形容词 different。"],
  ["hs_disaster", "disaster", "/dɪˈzɑːstə(r)/", "n.", "灾难；灾害", "The flood was a serious natural disaster.", "natural disaster", "常用于自然灾害类阅读。"],
  ["hs_economy", "economy", "/ɪˈkɒnəmi/", "n.", "经济", "Tourism plays an important role in the local economy.", "local economy", "economic 是形容词“经济的”。"],
  ["hs_educate", "educate", "/ˈedʒukeɪt/", "v.", "教育；培养", "Parents and schools should educate children together.", "educate sb. to do sth.", "名词 education，形容词 educational。"],
  ["hs_effort", "effort", "/ˈefət/", "n.", "努力", "Success requires time and effort.", "make an effort", "常用于作文表达努力。"],
  ["hs_encourage", "encourage", "/ɪnˈkʌrɪdʒ/", "v.", "鼓励；促进", "Teachers encourage students to ask questions.", "encourage sb. to do sth.", "反义 discourage。"],
  ["hs_environment", "environment", "/ɪnˈvaɪrənmənt/", "n.", "环境", "A quiet environment helps students study better.", "protect the environment", "自然环境和学习环境都可用。"],
  ["hs_establish", "establish", "/ɪˈstæblɪʃ/", "v.", "建立；确立", "The school established a new reading club.", "establish a system", "比 build 更正式。"],
  ["hs_exchange", "exchange", "/ɪksˈtʃeɪndʒ/", "n./v.", "交换；交流", "Students can exchange ideas after class.", "exchange ideas", "也可指交换生 exchange student。"],
  ["hs_experience", "experience", "/ɪkˈspɪəriəns/", "n./v.", "经历；经验；体验", "The trip was a valuable learning experience.", "gain experience", "作“经验”时常不可数，作“经历”时可数。"],
  ["hs_expert", "expert", "/ˈekspɜːt/", "n./adj.", "专家；熟练的", "Experts suggest that teenagers should sleep enough.", "an expert in", "名词专家，形容词熟练的。"],
  ["hs_express", "express", "/ɪkˈspres/", "v.", "表达；表示", "Writing helps students express their thoughts clearly.", "express one's opinion", "名词 expression。"],
  ["hs_figure", "figure", "/ˈfɪɡə(r)/", "n./v.", "数字；人物；认为", "The latest figures show a rise in online reading.", "figure out", "figure out 表示弄明白。"],
  ["hs_focus", "focus", "/ˈfəʊkəs/", "n./v.", "焦点；集中", "The lesson focuses on reading strategies.", "focus on", "on 后接名词或动名词。"],
  ["hs_function", "function", "/ˈfʌŋkʃn/", "n./v.", "功能；起作用", "The app has a useful review function.", "main function", "作动词时表示发挥作用。"],
  ["hs_generation", "generation", "/ˌdʒenəˈreɪʃn/", "n.", "一代人；产生", "Each generation has its own way of learning.", "younger generation", "常用于社会变化类阅读。"],
  ["hs_global", "global", "/ˈɡləʊbl/", "adj.", "全球的；全局的", "Climate change is a global problem.", "global problem", "名词 globe。"],
  ["hs_graduate", "graduate", "/ˈɡrædʒueɪt/", "v./n.", "毕业；毕业生", "She will graduate from high school next year.", "graduate from", "作动词时重音常在前或后，注意搭配 from。"],
  ["hs_habit", "habit", "/ˈhæbɪt/", "n.", "习惯", "Good habits are built through daily practice.", "form a habit", "常和 good/bad 搭配。"],
  ["hs_hesitate", "hesitate", "/ˈhezɪteɪt/", "v.", "犹豫", "Do not hesitate to ask for help.", "hesitate to do sth.", "常用于礼貌表达。"],
  ["hs_identify", "identify", "/aɪˈdentɪfaɪ/", "v.", "识别；确认", "The study identified several causes of stress.", "identify a problem", "阅读中常表示找出原因、问题。"],
  ["hs_ignore", "ignore", "/ɪɡˈnɔː(r)/", "v.", "忽视；不理会", "We should not ignore small problems.", "ignore advice", "常用于说明忽视风险或建议。"],
  ["hs_impact", "impact", "/ˈɪmpækt/", "n./v.", "影响；冲击", "Technology has a strong impact on education.", "have an impact on", "名词搭配非常高频。"],
  ["hs_improve", "improve", "/ɪmˈpruːv/", "v.", "改善；提高", "Practice can improve your spoken English.", "improve skills", "名词 improvement。"],
  ["hs_include", "include", "/ɪnˈkluːd/", "v.", "包括；包含", "The activities include reading and discussion.", "include doing sth.", "including 是介词，后接名词或动名词。"],
  ["hs_independent", "independent", "/ˌɪndɪˈpendənt/", "adj.", "独立的", "Teenagers should learn to be independent.", "be independent of", "名词 independence。"],
  ["hs_influence", "influence", "/ˈɪnfluəns/", "n./v.", "影响", "Parents have a great influence on children.", "have an influence on", "名词和动词都高频。"],
  ["hs_inspire", "inspire", "/ɪnˈspaɪə(r)/", "v.", "激励；启发", "The story inspired many students to keep trying.", "inspire sb. to do sth.", "常用于人物故事类阅读。"],
  ["hs_involve", "involve", "/ɪnˈvɒlv/", "v.", "涉及；包含", "The project involves collecting data from students.", "involve doing sth.", "后接动名词。"],
  ["hs_judge", "judge", "/dʒʌdʒ/", "v./n.", "判断；法官；裁判", "Do not judge a person only by appearance.", "judge by", "既可作动词也可作名词。"],
  ["hs_knowledge", "knowledge", "/ˈnɒlɪdʒ/", "n.", "知识", "Reading is a good way to gain knowledge.", "gain knowledge", "通常不可数。"],
  ["hs_lack", "lack", "/læk/", "n./v.", "缺乏", "Many students lack confidence in speaking English.", "lack confidence", "作动词时不加 of，作名词常用 lack of。"],
  ["hs_limit", "limit", "/ˈlɪmɪt/", "n./v.", "限制；限度", "Screen time should be limited during school days.", "limit time", "名词 limitation。"],
  ["hs_manage", "manage", "/ˈmænɪdʒ/", "v.", "管理；设法做到", "She managed to finish the task on time.", "manage to do sth.", "manage to do 表示成功做成。"],
  ["hs_measure", "measure", "/ˈmeʒə(r)/", "n./v.", "措施；测量", "The school took measures to improve safety.", "take measures", "作名词“措施”时常用复数。"],
  ["hs_method", "method", "/ˈmeθəd/", "n.", "方法", "This method can help students remember words.", "learning method", "比 way 更正式。"],
  ["hs_opportunity", "opportunity", "/ˌɒpəˈtjuːnəti/", "n.", "机会", "The competition gives students an opportunity to grow.", "an opportunity to do sth.", "作文中常用于表达机会。"],
  ["hs_organize", "organize", "/ˈɔːɡənaɪz/", "v.", "组织；安排", "Students organized a charity sale last weekend.", "organize an activity", "名词 organization。"],
  ["hs_participate", "participate", "/pɑːˈtɪsɪpeɪt/", "v.", "参加；参与", "More students are encouraged to participate in sports.", "participate in", "比 join in 更正式。"],
  ["hs_perform", "perform", "/pəˈfɔːm/", "v.", "表演；表现；执行", "The students performed well in the final exam.", "perform well", "performance 是名词。"],
  ["hs_personal", "personal", "/ˈpɜːsənl/", "adj.", "个人的；私人的", "Everyone has a personal learning style.", "personal information", "注意和 personnel 区分。"],
  ["hs_persuade", "persuade", "/pəˈsweɪd/", "v.", "说服", "He persuaded his friend to join the club.", "persuade sb. to do sth.", "强调成功说服。"],
  ["hs_positive", "positive", "/ˈpɒzətɪv/", "adj.", "积极的；肯定的", "A positive attitude can make a difference.", "positive attitude", "反义 negative。"],
  ["hs_pressure", "pressure", "/ˈpreʃə(r)/", "n.", "压力", "Students often feel pressure before exams.", "under pressure", "常用于学习压力话题。"],
  ["hs_prevent", "prevent", "/prɪˈvent/", "v.", "阻止；预防", "Exercise can prevent some health problems.", "prevent sb. from doing sth.", "from 可省略，但考试中常保留。"],
  ["hs_process", "process", "/ˈprəʊses/", "n./v.", "过程；处理", "Learning a language is a long process.", "learning process", "名词“过程”很高频。"],
  ["hs_promote", "promote", "/prəˈməʊt/", "v.", "促进；推广", "Reading can promote independent thinking.", "promote development", "常用于积极影响。"],
  ["hs_protect", "protect", "/prəˈtekt/", "v.", "保护", "We should protect wild animals and forests.", "protect...from", "名词 protection。"],
  ["hs_purpose", "purpose", "/ˈpɜːpəs/", "n.", "目的；意图", "The purpose of the activity is to raise awareness.", "the purpose of", "常用于阅读主旨题。"],
  ["hs_recommend", "recommend", "/ˌrekəˈmend/", "v.", "推荐；建议", "The teacher recommended this book to us.", "recommend sth. to sb.", "也可接 doing 或 that 从句。"],
  ["hs_reduce", "reduce", "/rɪˈdjuːs/", "v.", "减少；降低", "Walking to school can reduce pollution.", "reduce stress", "反义 increase。"],
  ["hs_reflect", "reflect", "/rɪˈflekt/", "v.", "反映；反思", "The story reflects the writer's childhood experience.", "reflect on", "reflect on 表示认真思考。"],
  ["hs_relationship", "relationship", "/rɪˈleɪʃnʃɪp/", "n.", "关系", "A good relationship between teachers and students matters.", "relationship between", "常用于人与人、事物之间的关系。"]
];

const extraHighSchoolWords = extraHighSchoolRows.map((row) => ({
  id: row[0],
  text: row[1],
  phonetic: row[2],
  level: "high_school",
  book: "高中核心",
  partOfSpeech: row[3],
  meaning: row[4],
  example: row[5],
  collocation: row[6],
  note: row[7]
}));

const extraCetRows = [
  ["cet_abandon", "abandon", "/əˈbændən/", "v.", "放弃；抛弃", "He had to abandon the plan because of limited time.", "abandon a plan", "正式写作和阅读中常表示彻底放弃。"],
  ["cet_accomplish", "accomplish", "/əˈkʌmplɪʃ/", "v.", "完成；实现", "The team accomplished the task ahead of time.", "accomplish a task", "比 finish 更正式，强调完成有难度的任务。"],
  ["cet_accumulate", "accumulate", "/əˈkjuːmjuleɪt/", "v.", "积累；聚积", "Students can accumulate vocabulary through daily reading.", "accumulate experience", "常用于知识、经验、财富的积累。"],
  ["cet_adequate", "adequate", "/ˈædɪkwət/", "adj.", "足够的；合格的", "Adequate sleep is necessary for effective learning.", "adequate support", "表示达到基本需求的足够。"],
  ["cet_adjust", "adjust", "/əˈdʒʌst/", "v.", "调整；适应", "You need to adjust your plan when conditions change.", "adjust to", "adjust to 表示适应新环境或变化。"],
  ["cet_advocate", "advocate", "/ˈædvəkeɪt/", "v./n.", "提倡；拥护者", "Many experts advocate regular exercise for teenagers.", "advocate doing sth.", "作动词时常接动名词。"],
  ["cet_alternative", "alternative", "/ɔːlˈtɜːnətɪv/", "n./adj.", "替代选择；可替代的", "Online courses offer an alternative to traditional classes.", "an alternative to", "to 是介词，后接名词或动名词。"],
  ["cet_anxiety", "anxiety", "/æŋˈzaɪəti/", "n.", "焦虑；担心", "Exam anxiety can affect students' performance.", "reduce anxiety", "常用于心理健康和考试压力话题。"],
  ["cet_appropriate", "appropriate", "/əˈprəʊpriət/", "adj.", "合适的；恰当的", "It is important to choose an appropriate method.", "be appropriate for", "正式语境中表示合适。"],
  ["cet_arise", "arise", "/əˈraɪz/", "v.", "出现；产生", "Problems may arise when people communicate online.", "arise from", "常表示问题、机会、情况出现。"],
  ["cet_assess", "assess", "/əˈses/", "v.", "评估；评价", "Teachers assess students' progress in different ways.", "assess progress", "名词 assessment。"],
  ["cet_assign", "assign", "/əˈsaɪn/", "v.", "分配；布置", "The teacher assigned a project to each group.", "assign a task", "常用于任务、作业、角色分配。"],
  ["cet_assist", "assist", "/əˈsɪst/", "v.", "帮助；协助", "Technology can assist students in learning languages.", "assist sb. in doing sth.", "比 help 更正式。"],
  ["cet_aware", "aware", "/əˈweə(r)/", "adj.", "意识到的；知道的", "Students should be aware of online safety.", "be aware of", "名词 awareness。"],
  ["cet_barrier", "barrier", "/ˈbæriə(r)/", "n.", "障碍；屏障", "Language can be a barrier to communication.", "a barrier to", "to 后接名词或动名词。"],
  ["cet_brief", "brief", "/briːf/", "adj.", "简短的；短暂的", "The speaker gave a brief introduction to the topic.", "a brief introduction", "常用于说明简短介绍或短暂时间。"],
  ["cet_capable", "capable", "/ˈkeɪpəbl/", "adj.", "有能力的", "Many teenagers are capable of solving complex problems.", "be capable of", "of 后接名词或动名词。"],
  ["cet_category", "category", "/ˈkætəɡəri/", "n.", "类别；种类", "The words are divided into different categories.", "fall into a category", "阅读中常用于分类。"],
  ["cet_commit", "commit", "/kəˈmɪt/", "v.", "承诺；投入；犯", "She is committed to improving her English.", "be committed to", "to 是介词，常接动名词。"],
  ["cet_complex", "complex", "/ˈkɒmpleks/", "adj.", "复杂的", "The article explains a complex social problem.", "complex problem", "比 difficult 更强调结构复杂。"],
  ["cet_component", "component", "/kəmˈpəʊnənt/", "n.", "组成部分；部件", "Vocabulary is an important component of language learning.", "key component", "常用于说明整体中的部分。"],
  ["cet_comprehensive", "comprehensive", "/ˌkɒmprɪˈhensɪv/", "adj.", "全面的；综合的", "The report gives a comprehensive analysis of the issue.", "comprehensive analysis", "正式阅读和写作中高频。"],
  ["cet_consistent", "consistent", "/kənˈsɪstənt/", "adj.", "一致的；持续的", "Consistent practice is the key to progress.", "be consistent with", "可表示前后一致，也可表示持续稳定。"],
  ["cet_consume", "consume", "/kənˈsjuːm/", "v.", "消耗；消费", "Watching short videos can consume a lot of time.", "consume energy", "常用于时间、能源、资源消耗。"],
  ["cet_context", "context", "/ˈkɒntekst/", "n.", "语境；背景", "You can guess the meaning from the context.", "in context", "词汇学习中非常重要。"],
  ["cet_contract", "contract", "/ˈkɒntrækt/", "n./v.", "合同；收缩；感染", "The company signed a contract with the school.", "sign a contract", "名词合同，动词有收缩、感染等义。"],
  ["cet_contrast", "contrast", "/ˈkɒntrɑːst/", "n./v.", "对比；形成对照", "The article draws a contrast between two lifestyles.", "in contrast", "常用于对比结构。"],
  ["cet_conventional", "conventional", "/kənˈvenʃənl/", "adj.", "传统的；常规的", "Online learning differs from conventional classroom learning.", "conventional method", "常和 traditional 接近。"],
  ["cet_cooperate", "cooperate", "/kəʊˈɒpəreɪt/", "v.", "合作；配合", "Students should cooperate with each other in group work.", "cooperate with", "名词 cooperation。"],
  ["cet_crucial", "crucial", "/ˈkruːʃl/", "adj.", "关键的；至关重要的", "Time management is crucial to exam success.", "be crucial to", "比 important 语气更强。"],
  ["cet_cycle", "cycle", "/ˈsaɪkl/", "n.", "循环；周期", "Sleep has a natural cycle.", "life cycle", "常用于科学和生活类阅读。"],
  ["cet_data", "data", "/ˈdeɪtə/", "n.", "数据；资料", "The data show that reading habits are changing.", "collect data", "学术阅读中高频。"],
  ["cet_definite", "definite", "/ˈdefɪnət/", "adj.", "明确的；确定的", "We need a definite answer before Friday.", "definite answer", "反义 indefinite。"],
  ["cet_demonstrate", "demonstrate", "/ˈdemənstreɪt/", "v.", "证明；展示", "The experiment demonstrates the importance of clean water.", "demonstrate that", "阅读中常表示证明观点。"],
  ["cet_depression", "depression", "/dɪˈpreʃn/", "n.", "抑郁；萧条", "Social support can reduce the risk of depression.", "economic depression", "可指心理抑郁，也可指经济萧条。"],
  ["cet_device", "device", "/dɪˈvaɪs/", "n.", "设备；装置", "Mobile devices are widely used in learning.", "digital device", "科技类阅读高频。"],
  ["cet_dimension", "dimension", "/daɪˈmenʃn/", "n.", "方面；维度；尺寸", "The problem has an important social dimension.", "new dimension", "不只表示尺寸，也表示方面。"],
  ["cet_distinct", "distinct", "/dɪˈstɪŋkt/", "adj.", "明显不同的；清楚的", "The two words have distinct meanings.", "distinct from", "强调清楚地区分。"],
  ["cet_diverse", "diverse", "/daɪˈvɜːs/", "adj.", "多样的；不同的", "Students come from diverse cultural backgrounds.", "diverse culture", "名词 diversity。"],
  ["cet_domestic", "domestic", "/dəˈmestɪk/", "adj.", "国内的；家庭的", "Domestic tourism has grown quickly in recent years.", "domestic market", "注意和 international 区分。"],
  ["cet_efficiency", "efficiency", "/ɪˈfɪʃnsi/", "n.", "效率", "Planning can improve learning efficiency.", "improve efficiency", "形容词 efficient。"],
  ["cet_emphasis", "emphasis", "/ˈemfəsɪs/", "n.", "强调；重视", "The school places emphasis on independent learning.", "place emphasis on", "on 后接名词或动名词。"],
  ["cet_enable", "enable", "/ɪˈneɪbl/", "v.", "使能够", "Technology enables students to learn anywhere.", "enable sb. to do sth.", "常用于科技带来的能力。"],
  ["cet_encounter", "encounter", "/ɪnˈkaʊntə(r)/", "v./n.", "遇到；遭遇", "Readers may encounter new words in the article.", "encounter a problem", "比 meet 更正式。"],
  ["cet_enhance", "enhance", "/ɪnˈhɑːns/", "v.", "提高；增强", "Reading can enhance language ability.", "enhance ability", "正式语境中常替代 improve。"],
  ["cet_ensure", "ensure", "/ɪnˈʃʊə(r)/", "v.", "确保；保证", "Good planning ensures better results.", "ensure that", "常用于说明保障措施。"],
  ["cet_estimate", "estimate", "/ˈestɪmeɪt/", "v./n.", "估计；估算", "Experts estimate that the number will continue to rise.", "estimate that", "名词和动词拼写相同。"],
  ["cet_evaluate", "evaluate", "/ɪˈvæljueɪt/", "v.", "评价；评估", "Students should evaluate information carefully.", "evaluate information", "常用于信息素养和研究类阅读。"],
  ["cet_eventually", "eventually", "/ɪˈventʃuəli/", "adv.", "最终；终于", "After months of practice, she eventually succeeded.", "eventually succeed", "强调经过过程后的最终结果。"],
  ["cet_exceed", "exceed", "/ɪkˈsiːd/", "v.", "超过；超出", "The cost exceeded our expectations.", "exceed expectations", "常用于数字、标准、预期。"],
  ["cet_expand", "expand", "/ɪkˈspænd/", "v.", "扩大；扩展", "The school plans to expand its online courses.", "expand knowledge", "反义 contract。"],
  ["cet_exposure", "exposure", "/ɪkˈspəʊʒə(r)/", "n.", "接触；暴露", "Exposure to English media can improve listening.", "exposure to", "to 是介词，后接名词。"],
  ["cet_facilitate", "facilitate", "/fəˈsɪlɪteɪt/", "v.", "促进；使便利", "Digital tools facilitate communication among students.", "facilitate communication", "正式词，常表示让某事更容易。"],
  ["cet_feature", "feature", "/ˈfiːtʃə(r)/", "n./v.", "特征；以……为特色", "The app features a simple review system.", "key feature", "名词特征，动词突出展示。"],
  ["cet_flexible", "flexible", "/ˈfleksəbl/", "adj.", "灵活的；可变通的", "A flexible schedule helps students manage time.", "flexible schedule", "反义 inflexible。"],
  ["cet_fundamental", "fundamental", "/ˌfʌndəˈmentl/", "adj.", "根本的；基础的", "Vocabulary is fundamental to language learning.", "be fundamental to", "比 basic 更正式。"],
  ["cet_generate", "generate", "/ˈdʒenəreɪt/", "v.", "产生；生成", "The new policy generated heated discussion.", "generate interest", "常用于产生影响、讨论、能量。"],
  ["cet_grant", "grant", "/ɡrɑːnt/", "v./n.", "授予；补助金", "The university granted him a scholarship.", "grant permission", "也可作名词表示补助金。"],
  ["cet_highlight", "highlight", "/ˈhaɪlaɪt/", "v./n.", "突出；强调；亮点", "The report highlights the value of early reading.", "highlight the importance", "写作和阅读中常表示强调。"],
  ["cet_illustrate", "illustrate", "/ˈɪləstreɪt/", "v.", "说明；阐明", "The example illustrates how habits are formed.", "illustrate a point", "常用于举例说明观点。"],
  ["cet_implement", "implement", "/ˈɪmplɪment/", "v.", "实施；执行", "The school implemented a new reading program.", "implement a policy", "常和 plan、policy、program 搭配。"],
  ["cet_imply", "imply", "/ɪmˈplaɪ/", "v.", "暗示；意味着", "His words imply that he disagrees with the plan.", "imply that", "阅读推断题高频词。"],
  ["cet_incentive", "incentive", "/ɪnˈsentɪv/", "n.", "激励；刺激", "Rewards can provide an incentive for students to read.", "an incentive for", "常用于动机和政策话题。"],
  ["cet_incident", "incident", "/ˈɪnsɪdənt/", "n.", "事件；事故", "The incident reminded students of the importance of safety.", "serious incident", "通常指具体事件。"],
  ["cet_initial", "initial", "/ɪˈnɪʃl/", "adj.", "最初的；开始的", "The initial results were better than expected.", "initial stage", "常用于阶段和结果描述。"],
  ["cet_innovation", "innovation", "/ˌɪnəˈveɪʃn/", "n.", "创新；新方法", "Innovation is important for future education.", "technological innovation", "作文和阅读高频主题词。"],
  ["cet_integrate", "integrate", "/ˈɪntɪɡreɪt/", "v.", "整合；融入", "The course integrates reading with speaking practice.", "integrate A with B", "强调把不同部分结合成整体。"],
  ["cet_interpret", "interpret", "/ɪnˈtɜːprət/", "v.", "解释；口译", "Different readers may interpret the story differently.", "interpret meaning", "名词 interpretation。"],
  ["cet_interval", "interval", "/ˈɪntəvl/", "n.", "间隔；间歇", "Reviewing words at intervals improves memory.", "at intervals", "和间隔复习概念相关。"],
  ["cet_investigate", "investigate", "/ɪnˈvestɪɡeɪt/", "v.", "调查；研究", "Researchers investigated the effects of sleep on memory.", "investigate the effect", "常用于研究和新闻语境。"],
  ["cet_justify", "justify", "/ˈdʒʌstɪfaɪ/", "v.", "证明……正当；为……辩护", "Can you justify your decision with evidence?", "justify a decision", "阅读中常用于论证。"],
  ["cet_label", "label", "/ˈleɪbl/", "n./v.", "标签；贴标签", "People should not label others too quickly.", "label sb. as", "作动词时可表示给人贴标签。"],
  ["cet_link", "link", "/lɪŋk/", "n./v.", "联系；连接", "Studies link exercise with better memory.", "link A with B", "常用于说明相关性。"],
  ["cet_majority", "majority", "/məˈdʒɒrəti/", "n.", "大多数", "The majority of students prefer short reviews.", "the majority of", "后接复数名词时谓语常用复数。"],
  ["cet_manual", "manual", "/ˈmænjuəl/", "adj./n.", "手工的；手册", "The machine can reduce manual work.", "manual labor", "作名词时表示手册。"],
  ["cet_maximum", "maximum", "/ˈmæksɪməm/", "n./adj.", "最大值；最大的", "The maximum number of questions is ten.", "maximum number", "反义 minimum。"],
  ["cet_mechanism", "mechanism", "/ˈmekənɪzəm/", "n.", "机制；机械装置", "Memory has a complex mechanism.", "working mechanism", "学术阅读中常表示机制。"],
  ["cet_modify", "modify", "/ˈmɒdɪfaɪ/", "v.", "修改；调整", "The teacher modified the task for beginners.", "modify a plan", "比 change 更正式。"],
  ["cet_monitor", "monitor", "/ˈmɒnɪtə(r)/", "v./n.", "监测；班长；显示器", "The app can monitor learning progress.", "monitor progress", "科技和教育语境高频。"],
  ["cet_motivate", "motivate", "/ˈməʊtɪveɪt/", "v.", "激励；促使", "Clear goals can motivate students to study.", "motivate sb. to do sth.", "名词 motivation。"],
  ["cet_obstacle", "obstacle", "/ˈɒbstəkl/", "n.", "障碍；阻碍", "Fear of mistakes is an obstacle to speaking.", "an obstacle to", "to 后接名词或动名词。"],
  ["cet_obtain", "obtain", "/əbˈteɪn/", "v.", "获得；取得", "Students can obtain useful information online.", "obtain information", "比 get 更正式。"],
  ["cet_occupy", "occupy", "/ˈɒkjupaɪ/", "v.", "占据；占用", "Homework occupies much of his evening.", "occupy time", "常用于时间、空间、注意力被占据。"],
  ["cet_option", "option", "/ˈɒpʃn/", "n.", "选择；选项", "Students have the option of studying online.", "have the option of", "和 choice 接近，但更偏可选方案。"],
  ["cet_overall", "overall", "/ˌəʊvərˈɔːl/", "adj./adv.", "总体的；总的来说", "Overall, the program improved students' confidence.", "overall effect", "常用于总结句。"],
  ["cet_potential", "potential", "/pəˈtenʃl/", "adj./n.", "潜在的；潜力", "Every student has the potential to improve.", "potential risk", "既可作形容词也可作名词。"],
  ["cet_prior", "prior", "/ˈpraɪə(r)/", "adj.", "先前的；优先的", "Prior knowledge helps readers understand new texts.", "prior to", "prior to 表示在……之前。"],
  ["cet_priority", "priority", "/praɪˈɒrəti/", "n.", "优先事项；优先权", "Health should be a top priority for students.", "top priority", "常用于排序和决策语境。"],
  ["cet_proportion", "proportion", "/prəˈpɔːʃn/", "n.", "比例；部分", "A large proportion of students use learning apps.", "a proportion of", "图表和调查类阅读高频。"],
  ["cet_pursue", "pursue", "/pəˈsjuː/", "v.", "追求；从事", "She decided to pursue a career in education.", "pursue a career", "常用于追求目标、事业、梦想。"]
];

const extraCetWords = extraCetRows.map((row) => ({
  id: row[0],
  text: row[1],
  phonetic: row[2],
  level: "cet",
  book: "四六级拓展",
  partOfSpeech: row[3],
  meaning: row[4],
  example: row[5],
  collocation: row[6],
  note: row[7]
}));

const allWords = [...words, ...extraElementaryWords, ...extraHighSchoolWords, ...extraCetWords];

const books = [
  {
    id: "elementary",
    name: "小学",
    description: "小学常见校园、家庭、出行和自然主题词汇。"
  },
  {
    id: "high_school",
    name: "高中",
    description: "高考阅读、完形和写作中最应该稳住的词。"
  },
  {
    id: "cet",
    name: "四六级",
    description: "适合词汇量较好的学生提前拓展，偏阅读和写作高频词。"
  }
];

module.exports = {
  words: allWords,
  books
};
